export default [
  {
    name: 'index',
    key: 'index',
    path: '/dashboard',
    icon: 'DashboardOutlined',
    component: './dashboard/Index',
  },
  {
    name: 'project',
    path: '/project',
    key: 'project',
    icon: 'AppstoreOutlined',
    component: './project/Index',
  },
  {
    name: 'project.run.detail',
    path: '/project/run/detail',
    key: 'project.run.detail',
    component: './project/RunDetail',
    hideInMenu: true,
  },
  {
    name: 'project.analyze',
    path: '/project/analyze',
    key: 'project.analyze',
    component: './project/Analyze',
    hideInMenu: true,
  },
  {
    name: 'run',
    path: '/run',
    key: 'run',
    icon: 'ExperimentOutlined',
    component: './run/Index',
  },
  {
    name: 'library',
    path: '/library',
    key: 'library',
    icon: 'DatabaseOutlined',
    component: './library/Index',
  },
  {
    name: 'libQC',
    path: '/library/libQC',
    key: 'libQC',
    icon: 'DatabaseOutlined',
    component: './library/LibQC',
    hideInMenu: true,
    layout: false,
  },
  {
    name: 'target',
    path: '/target',
    key: 'target',
    icon: 'AimOutlined',
    component: './target/Index',
  },
  {
    name: 'spectrum',
    path: '/spectrum',
    key: 'spectrum',
    icon: 'BarChartOutlined',
    component: './spectrum/Index',
  },
  {
    name: 'platform',
    path: '/platform',
    key: 'platform',
    icon: 'ProfileOutlined',
    component: './platform/Index',
  },
  {
    name: 'method',
    path: '/method',
    key: 'method',
    icon: 'ControlOutlined',
    component: './method/Index',
  },
  {
    name: 'overview',
    path: '/overview',
    key: 'overview',
    icon: 'DatabaseOutlined',
    component: './overview/Index',
  },
  {
    name: 'qc.target',
    path: '/qc/target',
    key: 'qc.target',
    component: './qc/Target',
    hideInMenu: true,
    layout: false,
  },
  {
    name: 'qc.untarget',
    path: '/qc/untarget',
    key: 'qc.untarget',
    component: './qc/Untarget',
    hideInMenu: true,
  },
  {
    name: 'qc.pre',
    path: '/qc/pre',
    key: 'qc.pre',
    component: './qc/Pre',
    hideInMenu: true,
    layout: false,
  },
  {
    name: 'monitor',
    path: '/monitor',
    key: 'monitor',
    icon: 'DingdingOutlined',
    component: './monitor/Index',
  },
  {
    name: 'trace',
    path: '/trace',
    key: 'trace',
    icon: 'ScheduleOutlined',
    component: './trace/Index',
  },
  {
    path: '/',
    redirect: '/dashboard',
  },
  {
    path:'*',
    layout:false,
    component: './404',
  },
];
